name: CI/CD Build & Deploy

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ghcr.io/k4ktu5-1337/devops-docker:latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: k4ktu5-1337
          password: ${{ secrets.CR_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT || 22 }}
          script_stop: true
          script: |
            set -e
            mkdir -p ${{ secrets.REPO_DIR }} || true
            cd ${{ secrets.REPO_DIR }} || exit 1

            if [ ! -d ".git" ]; then
              git clone https://github.com/${{ github.repository }} .
            else
              git reset --hard
              git pull origin main || true
            fi

            echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u k4ktu5-1337 --password-stdin
            docker pull ${{ env.IMAGE_NAME }} || true
            docker compose down || true
            docker compose up -d --build --remove-orphans
