name: Build & Deploy Local

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false  
          tags: devops-docker:latest

      - name: Deploy with docker-compose
        run: |
          cd /opt/blog/devops-docker    # Путь к твоему проекту на VM
          docker compose down || true
          docker compose up -d --build --remove-orphans
